In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv("D:\Desktop\salary.csv")
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [12]:
X = data["YearsExperience"].values.reshape(-1,1)
y = data["Salary"].values.reshape(-1,1)

In [13]:
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [16]:
lr.predict(np.array([[2.3,]])).round()

array([[47527.]])

In [17]:
lr.predict(np.array([[0,]]))

array([[25792.20019867]])

In [19]:
lr.intercept_

array([25792.20019867])

In [21]:
lr.coef_

array([[9449.96232146]])